### ISSUE TITLE
Ionic app is not working on all android devices

### ISSUE THREAD

**Issue by abhishek3999** [ionic-team/ionic-v1#388]
Hi,

I have created build in android.working on  android devices 5.1,6.1,7.1 and 8.But some of devices where UI disturbed.Its showing error as 'Error: [ng:areq] Argument 'reportInputController' is not a function, got undefined'.why this is happening on some of devices dont know.

Please do help asap.

Thanks,
